### ISSUE TITLE
snmp_simulator walk data

### ISSUE THREAD

**Issue by java-levia** [xiaopeng163/docker-compose-tpg#1]
May I ask what tool did you use to export the snmpwalk data used in snmp_simulator?

**Comment by xiaopeng163** [comment]
you can use snmpwalk to get data from a real device, then use it in the simulator, for example


```
snmpbulkwalk -v 2c -O en -C r5 -r 3 -t 3 -c <your community> hostname 1.3.6 > snmpwalk.data
```
